version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: beerus
    ports:
      - "5432:5432"
    volumes:
      - data_volume:/var/lib/postgresql/data

volumes:
  data_volume:
